eureka:
  client:
    fetchRegistry: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
    instance:
      preferIpAddress: true
app:
  jwt:
    secret: 1234
    expiration: 2592000
    issuer: spring-app-tasks-manager
    subject: user-details
  gateway:
    service-secret: 1234
    host: http://gateway:8080
spring:
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: validate
  kafka:
    producer:
      bootstrap-servers: 
        - kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    
  flyway:
    locations: classpath:/db/migration
