server:
  port: 8080
spring:
  application:
    name: gruop.service
  datasource:
    url: jdbc:postgresql://postgresdb:5432/group_service
    username: postgres
    password: 1234
  data:
    redis:
      database: 4
      host: redis
      port: 6379
      password: 1234
  kafka:
    consumer:
      group-id: user.service
