server:
  port: 8080
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true
spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user_route
            uri: lb://users.service
            predicates:
              - Path=/api/users/**