server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-route
            uri: lb://auth-service
            predicates:
              - Path=/api/auth/**