server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-route
            uri: lb://auth-service
            predicates:
              - Path=/api/auth/**
          - id: uuid-service
            uri: lb://uuid-service
            predicates:
              - Path=/api/uuid
              - Header=x-service-secret, ^secret$
        
