server:
  port: 8080
spring:
  application:
    name: orchestrator
  kafka:
    consumer:
      group-id: orchestrator
  data:
    redis:
      host: redis
      port: 6379
      username: redis
      password: 1234
