server:
  port: 8080
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgresdb:5432/auth_service
    username: postgres
    password: 1234
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: validate
  flyway:
    locations: classpath:/db/migration

app:
  jwt:
    secret: 1234
    expiration: 2592000
    issuer: spring-app-tasks-manager
    subject: user-details
    
  register:
    admin:
      password: 1234

