server:
  port: 8080
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgresdb:5432/auth_service
    username: postgres
    password: 1234
app:
  sign-up:
    admin:
      password: 1234

